### ISSUE TITLE
Discrete grouping variables with many levels

### ISSUE THREAD

**Issue by zcesur** [bklingen/MultivariateRelationship#2]
If we have a discrete factor with many levels, the resulting plot is quite ugly.

![groupingvar](https://user-images.githubusercontent.com/17045339/32928086-47bcd026-cb1e-11e7-82a0-59f18b6a934f.jpg)

In addition, this warning message is printed:

> 
> 
> Warning: The shape palette can deal with a maximum of 6 discrete values because more than 6 becomes difficult to discriminate; you
> have 67. Consider specifying shapes manually if you must have them.
> Warning: The following are not valid symbol codes:
> 'NA'
> Valid symbols include:
> '0', 'circle', '100', 'circle-open', '200', 'circle-dot', '300', 'circle-open-dot', '1', 'square', '101', 'square-open', '201', 'square-dot', '301', 'square-open-dot', '2', 'diamond', '102', 'diamond-open', '202', 'diamond-dot', '302', 'diamond-open-dot', '3', 'cross', '103', 'cross-open', '203', 'cross-dot', '303', 'cross-open-dot', '4', 'x', '104', 'x-open', '204', 'x-dot', '304', 'x-open-dot', '5', 'triangle-up', '105', 'triangle-up-open', '205', 'triangle-up-dot', '305', 'triangle-up-open-dot', '6', 'triangle-down', '106', 'triangle-down-open', '206', 'triangle-down-dot', '306', 'triangle-down-open-dot', '7', 'triangle-left', '107', 'triangle-left-open', '207', 'triangle-left-dot', '307', 'triangle-left-open-dot', '8', 'triangle-right', '108', 'triangle-right-open', '208', 'triangle-right-dot', '308', 'triangle-right-open-dot', '9', 'triangle-ne', '109', 'triangle-ne-open', '209', 'triangle-ne-dot', '309', 'trian [... truncated]

**Comment by bklingen** [comment]
Yes, I agree. We can do the following as I think you suggested: 
As soon as a factor with more than 6 levels (6 seems to be the maximum that can be handled) is selected for the grouping variable, treat it as if a continuous grouping variable were selected. We will probably have to add to the current line:

>   if(input$zvar=="None") plotdata$fill <- factor(1) else plotdata$fill <- df[,input$zvar]

and convert a factor that has more than 6 categories into a numeric with numerical values for the categories.
Or, as I'm thinking more about it, maybe we should just give the user a warning that more than 6 levels cannot be handled and this variable cannot be used as a grouping variable. (It may potentially be used as a x or y variable.) 
So, in essence, when we build our choices$z, we can just drop any variables that are i) factors and ii) have more than 6 categories. This way, we don't have to alert the user to anything. Such a variable is just not selectable from the drop-down menu for the grouping variable.

Let  me know if this last idea is the best implementation?

**Comment by zcesur** [comment]
The latter sounds like a clean and simple solution to me. Another way of doing it could be to take the most frequent 5 levels in the factor, and collapse the remaining into the 6th group "Other." Let me know which solution we should proceed with!

**Comment by bklingen** [comment]
Thinking about it, let's go with treating the variable as essentially 
continuous.

**Comment by zcesur** [comment]
Ok! How should we do that with, say, a vector of strings that cannot be coerced into numeric? For instance, what should a continuous scale of countries look like?

**Comment by zcesur** [comment]
Looks like this now:

![new](https://user-images.githubusercontent.com/17045339/34026992-c9403362-e127-11e7-843b-f8b96ae79c42.jpg)
