### ISSUE TITLE
Same color in ggplot-type scatterplot matrix from second tab as plotly scatterplot from first tab?

### ISSUE THREAD

**Issue by bklingen** [bklingen/MultivariateRelationship#7]
The scatterplot matrix in the second tab is generated with a special contributed ggplot2 package, called GGally.
Is there any way we can match the colors that appear for the groups in the scatterplot matrix (when using a categorical grouping variable) with the colors that appear in the plotly scatterplot with a group? 
Maybe the best way is to just get the color vector that plotly uses for its group and provide that in the ggplot call for the scatterplotmatrix?

**Comment by zcesur** [comment]
Added with 1ab578bd6b9a6ac23b8e79319afbda1112fa2375 and 586ce3e3b6a5a599e60f364ec9761ad23f1c9321. Let me know if you'd like to have the color of the data points vary based on grouping variable when we display smooth/linear trends. Currently the points are always red.
